/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacao;

import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.UIManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DatasetUtilities;


/**
 *
 * @author vitau
 */
public class Principal extends javax.swing.JFrame {
    JFrame frame_grafico;
  
   public CategoryDataset createDataset() {
        final double[][] data = new double[][]{
            {1.0, 4.0, 3.0, 5.0, 5.0, 7.0, 7.0, 8.0},
            {5.0, 7.0, 6.0, 8.0, 4.0, 4.0, 2.0, 1.0},
            {4.0, 3.0, 2.0, 3.0, 6.0, 3.0, 4.0, 3.0}
        };

        final CategoryDataset dataset = DatasetUtilities.createCategoryDataset(
                "", "", data
        );
        return dataset;
    }
   
    public Principal() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        SidePane = new javax.swing.JPanel();
        Panel_Opcao2 = new javax.swing.JPanel();
        Icon_Money = new javax.swing.JLabel();
        Label_Balanco = new javax.swing.JLabel();
        Panel_Opcao1 = new javax.swing.JPanel();
        Icon_Home = new javax.swing.JLabel();
        Label_Home = new javax.swing.JLabel();
        Panel_Opcao3 = new javax.swing.JPanel();
        Icon_Chart = new javax.swing.JLabel();
        Label_Relatorio = new javax.swing.JLabel();
        Label_Logo = new javax.swing.JLabel();
        Icon_Bank = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Panel_Opcao5 = new javax.swing.JPanel();
        Icon_Chart1 = new javax.swing.JLabel();
        Label_About = new javax.swing.JLabel();
        Panel_Opcao4 = new javax.swing.JPanel();
        Icon_Chart2 = new javax.swing.JLabel();
        Label_Analytic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Panel_Body = new javax.swing.JPanel();
        Panel_Principal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Label_We = new javax.swing.JLabel();
        Label_Heart = new javax.swing.JLabel();
        Label_Analytics = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Panel_Balanco = new javax.swing.JPanel();
        Panel_Relatorio = new javax.swing.JPanel();
        Panel_Analise = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelChart = new javax.swing.JPanel();
        Panel_Sobre = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIN311 Contabilidade - Análise Financeira");
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(51, 51, 51));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePane.setBackground(new java.awt.Color(11, 12, 12));
        SidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Opcao2.setBackground(new java.awt.Color(11, 12, 12));
        Panel_Opcao2.setForeground(new java.awt.Color(12, 13, 13));

        Icon_Money.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/money-bag.png"))); // NOI18N

        Label_Balanco.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Label_Balanco.setForeground(new java.awt.Color(255, 255, 255));
        Label_Balanco.setText("Balanço Patrimonial");
        Label_Balanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_BalancoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_BalancoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_BalancoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_Opcao2Layout = new javax.swing.GroupLayout(Panel_Opcao2);
        Panel_Opcao2.setLayout(Panel_Opcao2Layout);
        Panel_Opcao2Layout.setHorizontalGroup(
            Panel_Opcao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Opcao2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Icon_Money, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Balanco)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        Panel_Opcao2Layout.setVerticalGroup(
            Panel_Opcao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Opcao2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Opcao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Icon_Money, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Balanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SidePane.add(Panel_Opcao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, -1));

        Panel_Opcao1.setBackground(new java.awt.Color(51, 51, 51));

        Icon_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N

        Label_Home.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Label_Home.setForeground(new java.awt.Color(255, 255, 255));
        Label_Home.setText("Página Principal");
        Label_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_HomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_Opcao1Layout = new javax.swing.GroupLayout(Panel_Opcao1);
        Panel_Opcao1.setLayout(Panel_Opcao1Layout);
        Panel_Opcao1Layout.setHorizontalGroup(
            Panel_Opcao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Opcao1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Icon_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        Panel_Opcao1Layout.setVerticalGroup(
            Panel_Opcao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Opcao1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Opcao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Icon_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SidePane.add(Panel_Opcao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, -1));

        Panel_Opcao3.setBackground(new java.awt.Color(11, 12, 12));

        Icon_Chart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bar-chart.png"))); // NOI18N

        Label_Relatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_Relatorio.setForeground(new java.awt.Color(255, 255, 255));
        Label_Relatorio.setText("Relatórios");
        Label_Relatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_RelatorioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_RelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_RelatorioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_Opcao3Layout = new javax.swing.GroupLayout(Panel_Opcao3);
        Panel_Opcao3.setLayout(Panel_Opcao3Layout);
        Panel_Opcao3Layout.setHorizontalGroup(
            Panel_Opcao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Opcao3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Icon_Chart, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Relatorio)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        Panel_Opcao3Layout.setVerticalGroup(
            Panel_Opcao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Opcao3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Opcao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Icon_Chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SidePane.add(Panel_Opcao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, -1));

        Label_Logo.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        Label_Logo.setForeground(new java.awt.Color(102, 102, 102));
        Label_Logo.setText("We");
        SidePane.add(Label_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        Icon_Bank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paper-plane.png"))); // NOI18N
        SidePane.add(Icon_Bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        SidePane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Analytics");
        SidePane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        Panel_Opcao5.setBackground(new java.awt.Color(11, 12, 12));

        Icon_Chart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/more.png"))); // NOI18N

        Label_About.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_About.setForeground(new java.awt.Color(255, 255, 255));
        Label_About.setText("Sobre");
        Label_About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_AboutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_Opcao5Layout = new javax.swing.GroupLayout(Panel_Opcao5);
        Panel_Opcao5.setLayout(Panel_Opcao5Layout);
        Panel_Opcao5Layout.setHorizontalGroup(
            Panel_Opcao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Opcao5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Icon_Chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_About)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        Panel_Opcao5Layout.setVerticalGroup(
            Panel_Opcao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Opcao5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Opcao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Icon_Chart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SidePane.add(Panel_Opcao5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 290, -1));

        Panel_Opcao4.setBackground(new java.awt.Color(11, 12, 12));

        Icon_Chart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/file.png"))); // NOI18N

        Label_Analytic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_Analytic.setForeground(new java.awt.Color(255, 255, 255));
        Label_Analytic.setText("Análises");
        Label_Analytic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_AnalyticMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_AnalyticMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_AnalyticMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_Opcao4Layout = new javax.swing.GroupLayout(Panel_Opcao4);
        Panel_Opcao4.setLayout(Panel_Opcao4Layout);
        Panel_Opcao4Layout.setHorizontalGroup(
            Panel_Opcao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Opcao4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Icon_Chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Analytic)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        Panel_Opcao4Layout.setVerticalGroup(
            Panel_Opcao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Opcao4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Opcao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Icon_Chart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Analytic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SidePane.add(Panel_Opcao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 290, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("® Victor Tanabe 2018");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel8)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        SidePane.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 290, 50));

        bg.add(SidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 690));

        Panel_Body.setLayout(new java.awt.CardLayout());

        Tabela.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Avon Products Inc.", "R$ 2.233,30", null, "R$ 1.559,60", null, "R$ -257,20"},
                {"Natura Cosmetics Sa.", "R$ 7.056,31", null, "R$ 6.912,01", null, "R$ 1.634,75	"},
                {"Ulta Beauty Inc.", "R$ 1.536,24", null, "R$ 529,34", null, "R$ 1.550,22"}
            },
            new String [] {
                "Empresa", "Ativo Circulante", "Ativo NC", "Passivo Circulante", "Passivo NC", "Patrimônio Líquido"
            }
        ));
        jScrollPane1.setViewportView(Tabela);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrador");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N

        Label_We.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Label_We.setText("We");

        Label_Heart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/like.png"))); // NOI18N

        Label_Analytics.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Label_Analytics.setText("Analytics");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 102));
        jLabel4.setText("Histórico dos Dados das Empresas (2017)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Dados gerados através dos balanços patrimoniais disponíveis no site da BR.Investing referentes ao ano de 2017");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Administration/Dados");

        javax.swing.GroupLayout Panel_PrincipalLayout = new javax.swing.GroupLayout(Panel_Principal);
        Panel_Principal.setLayout(Panel_PrincipalLayout);
        Panel_PrincipalLayout.setHorizontalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                                .addComponent(Label_We)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_Heart, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_Analytics)
                                .addGap(777, 777, 777)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Panel_PrincipalLayout.setVerticalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5))
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Label_We, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Heart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Analytics))))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        Panel_Body.add(Panel_Principal, "card2");

        javax.swing.GroupLayout Panel_BalancoLayout = new javax.swing.GroupLayout(Panel_Balanco);
        Panel_Balanco.setLayout(Panel_BalancoLayout);
        Panel_BalancoLayout.setHorizontalGroup(
            Panel_BalancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        Panel_BalancoLayout.setVerticalGroup(
            Panel_BalancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        Panel_Body.add(Panel_Balanco, "card3");

        javax.swing.GroupLayout Panel_RelatorioLayout = new javax.swing.GroupLayout(Panel_Relatorio);
        Panel_Relatorio.setLayout(Panel_RelatorioLayout);
        Panel_RelatorioLayout.setHorizontalGroup(
            Panel_RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        Panel_RelatorioLayout.setVerticalGroup(
            Panel_RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        Panel_Body.add(Panel_Relatorio, "card4");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 102));
        jLabel9.setText("Análise Geral");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Análise Situacional das 3 Empresas");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setText("883.1");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 102));
        jLabel12.setText("Giro do Ativo");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setText("883.1");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 102));
        jLabel14.setText("Liquidez Geral");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setText("883.1");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 102));
        jLabel16.setText("Rentabildade");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(43, 43, 43));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Insira aqui a análise geral referente aos balanços analisados");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        panelChart.setBackground(new java.awt.Color(51, 51, 51));
        panelChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout Panel_AnaliseLayout = new javax.swing.GroupLayout(Panel_Analise);
        Panel_Analise.setLayout(Panel_AnaliseLayout);
        Panel_AnaliseLayout.setHorizontalGroup(
            Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                                .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 673, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                            .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13)
                                .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        Panel_AnaliseLayout.setVerticalGroup(
            Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7))
                    .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(62, 62, 62)
                .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                        .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel15))
                    .addComponent(panelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        Panel_Body.add(Panel_Analise, "card5");

        javax.swing.GroupLayout Panel_SobreLayout = new javax.swing.GroupLayout(Panel_Sobre);
        Panel_Sobre.setLayout(Panel_SobreLayout);
        Panel_SobreLayout.setHorizontalGroup(
            Panel_SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        Panel_SobreLayout.setVerticalGroup(
            Panel_SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        Panel_Body.add(Panel_Sobre, "card6");

        bg.add(Panel_Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1070, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Label_BalancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_BalancoMouseClicked
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card3");
    }//GEN-LAST:event_Label_BalancoMouseClicked

    private void Label_RelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_RelatorioMouseClicked
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card4");
    }//GEN-LAST:event_Label_RelatorioMouseClicked

    private void Label_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_HomeMouseClicked
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card2");
    }//GEN-LAST:event_Label_HomeMouseClicked

    private void Label_AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AboutMouseClicked
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card6");
    }//GEN-LAST:event_Label_AboutMouseClicked

    private void Label_AnalyticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AnalyticMouseClicked
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card5");
        
        CategoryDataset dataset = createDataset();
        JFreeChart chart = ChartFactory.createStackedAreaChart("", "", "", dataset);
        chart.setBackgroundPaint(new Color(43, 43, 43));
        chart.setBorderVisible(false);
        chart.setBorderPaint(new Color(54, 63, 73));
        chart.getCategoryPlot().setBackgroundPaint(new Color(43, 43, 43));
        chart.getCategoryPlot().setDomainGridlinePaint(new Color(54, 63, 73));
        chart.getCategoryPlot().setDomainGridlinesVisible(false);
        chart.getCategoryPlot().setOutlinePaint(new Color(54, 63, 73));

        ChartPanel cp = new ChartPanel(chart);
        cp.setBackground(new Color(43, 43, 43));

        panelChart.removeAll();
        panelChart.add(cp, BorderLayout.CENTER);
        panelChart.validate();
    }//GEN-LAST:event_Label_AnalyticMouseClicked

    private void Label_RelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_RelatorioMouseEntered
       Panel_Opcao3.setBackground(new java.awt.Color(51, 51, 51)); 
       Label_Relatorio.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N 
    }//GEN-LAST:event_Label_RelatorioMouseEntered

    private void Label_RelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_RelatorioMouseExited
       Panel_Opcao3.setBackground(new java.awt.Color(11, 12, 12));
       Label_Relatorio.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N 
    }//GEN-LAST:event_Label_RelatorioMouseExited

    private void Label_BalancoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_BalancoMouseEntered
        Panel_Opcao2.setBackground(new java.awt.Color(51, 51, 51));
        Label_Balanco.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N 
    }//GEN-LAST:event_Label_BalancoMouseEntered

    private void Label_BalancoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_BalancoMouseExited
        Panel_Opcao2.setBackground(new java.awt.Color(11, 12, 12));
        Label_Balanco.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    }//GEN-LAST:event_Label_BalancoMouseExited

    private void Label_AnalyticMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AnalyticMouseEntered
       Panel_Opcao4.setBackground(new java.awt.Color(51, 51, 51)); 
       Label_Analytic.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N   
    }//GEN-LAST:event_Label_AnalyticMouseEntered

    private void Label_AnalyticMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AnalyticMouseExited
        Panel_Opcao4.setBackground(new java.awt.Color(11, 12, 12));
        Label_Analytic.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N 
    }//GEN-LAST:event_Label_AnalyticMouseExited

    private void Label_AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AboutMouseEntered
        Panel_Opcao5.setBackground(new java.awt.Color(51, 51, 51));
        Label_About.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N   
    }//GEN-LAST:event_Label_AboutMouseEntered

    private void Label_AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AboutMouseExited
        Panel_Opcao5.setBackground(new java.awt.Color(11, 12, 12));
        Label_About.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N   
    }//GEN-LAST:event_Label_AboutMouseExited
        
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                try{
          UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());}   
                catch (Exception e){
          e.printStackTrace();}
                new Principal().setVisible(true);
            }});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon_Bank;
    private javax.swing.JLabel Icon_Chart;
    private javax.swing.JLabel Icon_Chart1;
    private javax.swing.JLabel Icon_Chart2;
    private javax.swing.JLabel Icon_Home;
    private javax.swing.JLabel Icon_Money;
    private javax.swing.JLabel Label_About;
    private javax.swing.JLabel Label_Analytic;
    private javax.swing.JLabel Label_Analytics;
    private javax.swing.JLabel Label_Balanco;
    private javax.swing.JLabel Label_Heart;
    private javax.swing.JLabel Label_Home;
    private javax.swing.JLabel Label_Logo;
    private javax.swing.JLabel Label_Relatorio;
    private javax.swing.JLabel Label_We;
    private javax.swing.JPanel Panel_Analise;
    private javax.swing.JPanel Panel_Balanco;
    private javax.swing.JPanel Panel_Body;
    private javax.swing.JPanel Panel_Opcao1;
    private javax.swing.JPanel Panel_Opcao2;
    private javax.swing.JPanel Panel_Opcao3;
    private javax.swing.JPanel Panel_Opcao4;
    private javax.swing.JPanel Panel_Opcao5;
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JPanel Panel_Relatorio;
    private javax.swing.JPanel Panel_Sobre;
    private javax.swing.JPanel SidePane;
    private javax.swing.JTable Tabela;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelChart;
    // End of variables declaration//GEN-END:variables
}
