/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacao;

import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.UIManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DatasetUtilities;


/**
 *
 * @author vitau
 */
public class Principal extends javax.swing.JFrame {
    JFrame frame_grafico;
  
   public CategoryDataset createDataset() {
        final double[][] data = new double[][]{
            {1.0, 4.0, 3.0, 5.0, 5.0, 7.0, 7.0, 8.0},
            {5.0, 7.0, 6.0, 8.0, 4.0, 4.0, 2.0, 1.0},
            {4.0, 3.0, 2.0, 3.0, 6.0, 3.0, 4.0, 3.0}
        };

        final CategoryDataset dataset = DatasetUtilities.createCategoryDataset(
                "", "", data
        );
        return dataset;
    }
   
    public Principal() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        SidePane = new javax.swing.JPanel();
        Panel_Opcao2 = new javax.swing.JPanel();
        Icon_Money = new javax.swing.JLabel();
        Label_Balanco = new javax.swing.JLabel();
        Panel_Opcao1 = new javax.swing.JPanel();
        Icon_Home = new javax.swing.JLabel();
        Label_Home = new javax.swing.JLabel();
        Panel_Opcao3 = new javax.swing.JPanel();
        Icon_Chart = new javax.swing.JLabel();
        Label_Relatorio = new javax.swing.JLabel();
        Label_Logo = new javax.swing.JLabel();
        Icon_Bank = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Panel_Opcao5 = new javax.swing.JPanel();
        Icon_Chart1 = new javax.swing.JLabel();
        Label_About = new javax.swing.JLabel();
        Panel_Opcao4 = new javax.swing.JPanel();
        Icon_Chart2 = new javax.swing.JLabel();
        Label_Analytic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Panel_Body = new javax.swing.JPanel();
        Panel_Principal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Label_We = new javax.swing.JLabel();
        Label_Heart = new javax.swing.JLabel();
        Label_Analytics = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Panel_BalancoAvon = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BP_Empresa1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Panel_Relatorio = new javax.swing.JPanel();
        Panel_Analise = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelChart = new javax.swing.JPanel();
        Panel_Sobre = new javax.swing.JPanel();
        Panel_BalancoNatura = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        BP_Empresa3 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Panel_BalancoUltaBeauty = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        BP_Empresa4 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIN311 Contabilidade - Análise Financeira");
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(51, 51, 51));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePane.setBackground(new java.awt.Color(11, 12, 12));
        SidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Opcao2.setBackground(new java.awt.Color(11, 12, 12));
        Panel_Opcao2.setForeground(new java.awt.Color(12, 13, 13));

        Icon_Money.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/money-bag.png"))); // NOI18N

        Label_Balanco.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Label_Balanco.setForeground(new java.awt.Color(255, 255, 255));
        Label_Balanco.setText("Balanço Patrimonial");
        Label_Balanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_BalancoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_BalancoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_BalancoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_Opcao2Layout = new javax.swing.GroupLayout(Panel_Opcao2);
        Panel_Opcao2.setLayout(Panel_Opcao2Layout);
        Panel_Opcao2Layout.setHorizontalGroup(
            Panel_Opcao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Opcao2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Icon_Money, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Balanco)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        Panel_Opcao2Layout.setVerticalGroup(
            Panel_Opcao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Opcao2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Opcao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Icon_Money, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Balanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SidePane.add(Panel_Opcao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, -1));

        Panel_Opcao1.setBackground(new java.awt.Color(51, 51, 51));

        Icon_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N

        Label_Home.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Label_Home.setForeground(new java.awt.Color(255, 255, 255));
        Label_Home.setText("Página Principal");
        Label_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_HomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_Opcao1Layout = new javax.swing.GroupLayout(Panel_Opcao1);
        Panel_Opcao1.setLayout(Panel_Opcao1Layout);
        Panel_Opcao1Layout.setHorizontalGroup(
            Panel_Opcao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Opcao1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Icon_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        Panel_Opcao1Layout.setVerticalGroup(
            Panel_Opcao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Opcao1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Opcao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Icon_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SidePane.add(Panel_Opcao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, -1));

        Panel_Opcao3.setBackground(new java.awt.Color(11, 12, 12));

        Icon_Chart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bar-chart.png"))); // NOI18N

        Label_Relatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_Relatorio.setForeground(new java.awt.Color(255, 255, 255));
        Label_Relatorio.setText("Relatórios");
        Label_Relatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_RelatorioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_RelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_RelatorioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_Opcao3Layout = new javax.swing.GroupLayout(Panel_Opcao3);
        Panel_Opcao3.setLayout(Panel_Opcao3Layout);
        Panel_Opcao3Layout.setHorizontalGroup(
            Panel_Opcao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Opcao3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Icon_Chart, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Relatorio)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        Panel_Opcao3Layout.setVerticalGroup(
            Panel_Opcao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Opcao3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Opcao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Icon_Chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SidePane.add(Panel_Opcao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, -1));

        Label_Logo.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        Label_Logo.setForeground(new java.awt.Color(102, 102, 102));
        Label_Logo.setText("We");
        SidePane.add(Label_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        Icon_Bank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paper-plane.png"))); // NOI18N
        SidePane.add(Icon_Bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        SidePane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Analytics");
        SidePane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        Panel_Opcao5.setBackground(new java.awt.Color(11, 12, 12));

        Icon_Chart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/more.png"))); // NOI18N

        Label_About.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_About.setForeground(new java.awt.Color(255, 255, 255));
        Label_About.setText("Sobre");
        Label_About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_AboutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_Opcao5Layout = new javax.swing.GroupLayout(Panel_Opcao5);
        Panel_Opcao5.setLayout(Panel_Opcao5Layout);
        Panel_Opcao5Layout.setHorizontalGroup(
            Panel_Opcao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Opcao5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Icon_Chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_About)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        Panel_Opcao5Layout.setVerticalGroup(
            Panel_Opcao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Opcao5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Opcao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Icon_Chart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SidePane.add(Panel_Opcao5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 290, -1));

        Panel_Opcao4.setBackground(new java.awt.Color(11, 12, 12));

        Icon_Chart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/file.png"))); // NOI18N

        Label_Analytic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_Analytic.setForeground(new java.awt.Color(255, 255, 255));
        Label_Analytic.setText("Análises");
        Label_Analytic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_AnalyticMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_AnalyticMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_AnalyticMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_Opcao4Layout = new javax.swing.GroupLayout(Panel_Opcao4);
        Panel_Opcao4.setLayout(Panel_Opcao4Layout);
        Panel_Opcao4Layout.setHorizontalGroup(
            Panel_Opcao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Opcao4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Icon_Chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Analytic)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        Panel_Opcao4Layout.setVerticalGroup(
            Panel_Opcao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Opcao4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Opcao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Icon_Chart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Analytic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SidePane.add(Panel_Opcao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 290, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("® Victor Tanabe 2018");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel8)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        SidePane.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 290, 50));

        bg.add(SidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 690));

        Panel_Body.setLayout(new java.awt.CardLayout());

        Tabela.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Avon Products Inc.", "R$ 2.233,30", null, "R$ 1.559,60", null, "R$ -257,20"},
                {"Natura Cosmetics Sa.", "R$ 7.056,31", null, "R$ 6.912,01", null, "R$ 1.634,75	"},
                {"Ulta Beauty Inc.", "R$ 1.536,24", null, "R$ 529,34", null, "R$ 1.550,22"}
            },
            new String [] {
                "Empresa", "Ativo Circulante", "Ativo NC", "Passivo Circulante", "Passivo NC", "Patrimônio Líquido"
            }
        ));
        jScrollPane1.setViewportView(Tabela);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrador");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N

        Label_We.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Label_We.setText("We");

        Label_Heart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/like.png"))); // NOI18N

        Label_Analytics.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Label_Analytics.setText("Analytics");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 102));
        jLabel4.setText("Histórico dos Dados das Empresas (2017)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Dados gerados através dos balanços patrimoniais disponíveis no site da BR.Investing referentes ao ano de 2017");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Administration/Dados");

        javax.swing.GroupLayout Panel_PrincipalLayout = new javax.swing.GroupLayout(Panel_Principal);
        Panel_Principal.setLayout(Panel_PrincipalLayout);
        Panel_PrincipalLayout.setHorizontalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                                .addComponent(Label_We)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_Heart, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_Analytics)
                                .addGap(777, 777, 777)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Panel_PrincipalLayout.setVerticalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5))
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Label_We, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Heart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Analytics))))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        Panel_Body.add(Panel_Principal, "card2");

        Panel_BalancoAvon.setPreferredSize(new java.awt.Dimension(1070, 690));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 255, 102));
        jLabel17.setText("Balanço Patrimonial - Avon Products Inc.");

        BP_Empresa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Total do Ativo",  new Float(3697.9),  new Float(3418.9)},
                {"Imobilizado Liquido",  new Float(702.7),  new Float(711.3)},
                {"Imobilizado Bruto",  new Float(1481.9),  new Float(1424.1)},
                {"Deprec. Acumulada",  new Float(-779.2),  new Float(-712.8)},
                {"Ágio, Líquido",  new Float(95.7),  new Float(93.6)},
                {"Intangiveis, LIq",  new Float(85.2),  new Float(83.9)},
                {"Invest. LP", null,  new Float(68.0)},
                {"Realizável LP",  new Float(75.6),  new Float(156.9)},
                {"Outros Ativos LP",  new Float(505.4),  new Float(312.9)},
                {null, null, null},
                {"Total do Passivo",  new Float(1559.6),  new Float(1485.7)},
                {"A Pagar / Acumulado",  new Float(832.2),  new Float(765.1)},
                {"Investimentos CP",  new Float(535.9),  new Float(531.1)},
                {"Empréstimos CP / Notas",  new Float(22.6), null},
                {"Parcela Circ. das Obrigações de Arredondamento Merc.",  new Float(3.1),  new Float(8.1)},
                {"Outros Passivos Circ.",  new Float(165.8),  new Float(171.4)},
                {null, null, null},
                {"Total do Patrimônio Líquido",  new Float(-257.2),  new Float(-403.3)},
                {"Ágio, Liquido",  new Float(467.8),  new Float(444.7)},
                {"Ações Ordinárias",  new Float(189.7),  new Float(188.8)},
                {"Capital Social",  new Float(2291.2),  new Float(2273.9)},
                {"Lucros Retidos",  new Float(2320.3),  new Float(2322.2)},
                {"Ações em Tesouraria",  new Float(-4600.0),  new Float(-4599.7)},
                {"Outros Patrimônios",  new Float(-926.2),  new Float(-1033.2)},
                {null, null, null},
                {"Total do Passivo e Patrimônio Líquido",  new Float(3697.9),  new Float(3418.9)}
            },
            new String [] {
                "Dado", "2016", "2017"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(BP_Empresa1);

        jScrollPane4.setBackground(new java.awt.Color(43, 43, 43));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(43, 43, 43));
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Razão Social: Avon Products Inc.\nTipo: Empresa de Capital Aberto\n\nAvon Cosméticos ou simplesmente Avon, é uma empresa norte-americana de cosméticos. Sua história teve início em 1886 quando David McConnell iniciou a Califórnia Perfume Company, em Manhattan, Nova York. O nome Avon, pelo qual ficaria mundialmente conhecida, só surgiu em 1939, inspirado na cidade natal do escritor William Shakespeare, Stratford-upon-Avon. No Brasil ela só apareceu em 1952. Ao longo dos anos a Avon desenvolveu diversas linhas de produto, variando entre fragrâncias, maquiagem, cabelos e cuidados da pele, além de uma linha infantil. Através do sistema de venda por folhetos e revendedoras, atingindo significativa participação no mercado de beleza.");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea2);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/avon-logo.png"))); // NOI18N

        jButton2.setText("Próximo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_BalancoAvonLayout = new javax.swing.GroupLayout(Panel_BalancoAvon);
        Panel_BalancoAvon.setLayout(Panel_BalancoAvonLayout);
        Panel_BalancoAvonLayout.setHorizontalGroup(
            Panel_BalancoAvonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BalancoAvonLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(Panel_BalancoAvonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Panel_BalancoAvonLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(Panel_BalancoAvonLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_BalancoAvonLayout.setVerticalGroup(
            Panel_BalancoAvonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BalancoAvonLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(Panel_BalancoAvonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(Panel_BalancoAvonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_BalancoAvonLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel18)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        Panel_Body.add(Panel_BalancoAvon, "card3");

        javax.swing.GroupLayout Panel_RelatorioLayout = new javax.swing.GroupLayout(Panel_Relatorio);
        Panel_Relatorio.setLayout(Panel_RelatorioLayout);
        Panel_RelatorioLayout.setHorizontalGroup(
            Panel_RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        Panel_RelatorioLayout.setVerticalGroup(
            Panel_RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        Panel_Body.add(Panel_Relatorio, "card4");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 102));
        jLabel9.setText("Análise Geral");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Análise Situacional das 3 Empresas");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setText("883.1");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 102));
        jLabel12.setText("Giro do Ativo");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setText("883.1");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 102));
        jLabel14.setText("Liquidez Geral");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setText("883.1");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 102));
        jLabel16.setText("Rentabildade");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(43, 43, 43));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Insira aqui a análise geral referente aos balanços analisados");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        panelChart.setBackground(new java.awt.Color(51, 51, 51));
        panelChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout Panel_AnaliseLayout = new javax.swing.GroupLayout(Panel_Analise);
        Panel_Analise.setLayout(Panel_AnaliseLayout);
        Panel_AnaliseLayout.setHorizontalGroup(
            Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                                .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 673, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel10)
                    .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                        .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        Panel_AnaliseLayout.setVerticalGroup(
            Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7))
                    .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(62, 62, 62)
                .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                        .addGroup(Panel_AnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel_AnaliseLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel15))
                    .addComponent(panelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        Panel_Body.add(Panel_Analise, "card5");

        javax.swing.GroupLayout Panel_SobreLayout = new javax.swing.GroupLayout(Panel_Sobre);
        Panel_Sobre.setLayout(Panel_SobreLayout);
        Panel_SobreLayout.setHorizontalGroup(
            Panel_SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        Panel_SobreLayout.setVerticalGroup(
            Panel_SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        Panel_Body.add(Panel_Sobre, "card6");

        Panel_BalancoNatura.setPreferredSize(new java.awt.Dimension(1070, 690));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 255, 102));
        jLabel21.setText("Balanço Patrimonial - Natura Cosmetics SA.");

        BP_Empresa3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Total do Ativo",  new Float(3697.9),  new Float(3418.9)},
                {"Imobilizado Liquido",  new Float(702.7),  new Float(711.3)},
                {"Imobilizado Bruto",  new Float(1481.9),  new Float(1424.1)},
                {"Deprec. Acumulada",  new Float(-779.2),  new Float(-712.8)},
                {"Ágio, Líquido",  new Float(95.7),  new Float(93.6)},
                {"Intangiveis, LIq",  new Float(85.2),  new Float(83.9)},
                {"Invest. LP", null,  new Float(68.0)},
                {"Realizável LP",  new Float(75.6),  new Float(156.9)},
                {"Outros Ativos LP",  new Float(505.4),  new Float(312.9)},
                {null, null, null},
                {"Total do Passivo",  new Float(1559.6),  new Float(1485.7)},
                {"A Pagar / Acumulado",  new Float(832.2),  new Float(765.1)},
                {"Investimentos CP",  new Float(535.9),  new Float(531.1)},
                {"Empréstimos CP / Notas",  new Float(22.6), null},
                {"Parcela Circ. das Obrigações de Arredondamento Merc.",  new Float(3.1),  new Float(8.1)},
                {"Outros Passivos Circ.",  new Float(165.8),  new Float(171.4)},
                {null, null, null},
                {"Total do Patrimônio Líquido",  new Float(-257.2),  new Float(-403.3)},
                {"Ágio, Liquido",  new Float(467.8),  new Float(444.7)},
                {"Ações Ordinárias",  new Float(189.7),  new Float(188.8)},
                {"Capital Social",  new Float(2291.2),  new Float(2273.9)},
                {"Lucros Retidos",  new Float(2320.3),  new Float(2322.2)},
                {"Ações em Tesouraria",  new Float(-4600.0),  new Float(-4599.7)},
                {"Outros Patrimônios",  new Float(-926.2),  new Float(-1033.2)},
                {null, null, null},
                {"Total do Passivo e Patrimônio Líquido",  new Float(3697.9),  new Float(3418.9)}
            },
            new String [] {
                "Dado", "2016", "2017"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(BP_Empresa3);

        jScrollPane8.setBackground(new java.awt.Color(43, 43, 43));

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(43, 43, 43));
        jTextArea4.setColumns(20);
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Razão Social: Natura Cosmetics Inc.\nTipo: Empresa de Capital Aberto\n\nNatura é uma empresa brasileira que atua no setor de produtos de tratamento para o rosto, corpo, sabonetes, barba, desodorantes, óleos corporais, maquiagem, perfumaria, cabelos, proteção solar, e infantil. Fundada em 1969 por Antônio Luiz Seabra, hoje está presente no Brasil, Argentina, Chile, Colômbia, México, Peru, Venezuela,França e Estados Unidos, além de outros 63 países indiretamente. O número de funcionários, chamados na empresa de \"colaboradores\", atingiu 7.000 em 2013 e o de consultoras estimado em 1,5 milhão. A Natura foi criada em agosto de 1969 por Antônio Luiz Seabra após abrir uma loja e uma pequena fábrica no bairro da Vila Mariana em São Paulo, em 1974 a empresa deixou de oferecer seus produtos em lojas e passou a vendê-los no modelo de venda-direta.");
        jTextArea4.setWrapStyleWord(true);
        jScrollPane8.setViewportView(jTextArea4);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/natura-logo.png"))); // NOI18N

        jButton3.setText("Próximo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_BalancoNaturaLayout = new javax.swing.GroupLayout(Panel_BalancoNatura);
        Panel_BalancoNatura.setLayout(Panel_BalancoNaturaLayout);
        Panel_BalancoNaturaLayout.setHorizontalGroup(
            Panel_BalancoNaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BalancoNaturaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(Panel_BalancoNaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_BalancoNaturaLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(Panel_BalancoNaturaLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        Panel_BalancoNaturaLayout.setVerticalGroup(
            Panel_BalancoNaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BalancoNaturaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(Panel_BalancoNaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(Panel_BalancoNaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_BalancoNaturaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel22)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        Panel_Body.add(Panel_BalancoNatura, "card7");

        Panel_BalancoUltaBeauty.setPreferredSize(new java.awt.Dimension(1070, 690));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 255, 102));
        jLabel23.setText("Balanço Patrimonial - Ulta Beauty Inc.");

        BP_Empresa4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Total do Ativo",  new Float(3697.9),  new Float(3418.9)},
                {"Imobilizado Liquido",  new Float(702.7),  new Float(711.3)},
                {"Imobilizado Bruto",  new Float(1481.9),  new Float(1424.1)},
                {"Deprec. Acumulada",  new Float(-779.2),  new Float(-712.8)},
                {"Ágio, Líquido",  new Float(95.7),  new Float(93.6)},
                {"Intangiveis, LIq",  new Float(85.2),  new Float(83.9)},
                {"Invest. LP", null,  new Float(68.0)},
                {"Realizável LP",  new Float(75.6),  new Float(156.9)},
                {"Outros Ativos LP",  new Float(505.4),  new Float(312.9)},
                {null, null, null},
                {"Total do Passivo",  new Float(1559.6),  new Float(1485.7)},
                {"A Pagar / Acumulado",  new Float(832.2),  new Float(765.1)},
                {"Investimentos CP",  new Float(535.9),  new Float(531.1)},
                {"Empréstimos CP / Notas",  new Float(22.6), null},
                {"Parcela Circ. das Obrigações de Arredondamento Merc.",  new Float(3.1),  new Float(8.1)},
                {"Outros Passivos Circ.",  new Float(165.8),  new Float(171.4)},
                {null, null, null},
                {"Total do Patrimônio Líquido",  new Float(-257.2),  new Float(-403.3)},
                {"Ágio, Liquido",  new Float(467.8),  new Float(444.7)},
                {"Ações Ordinárias",  new Float(189.7),  new Float(188.8)},
                {"Capital Social",  new Float(2291.2),  new Float(2273.9)},
                {"Lucros Retidos",  new Float(2320.3),  new Float(2322.2)},
                {"Ações em Tesouraria",  new Float(-4600.0),  new Float(-4599.7)},
                {"Outros Patrimônios",  new Float(-926.2),  new Float(-1033.2)},
                {null, null, null},
                {"Total do Passivo e Patrimônio Líquido",  new Float(3697.9),  new Float(3418.9)}
            },
            new String [] {
                "Dado", "2016", "2017"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(BP_Empresa4);

        jScrollPane10.setBackground(new java.awt.Color(43, 43, 43));

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(43, 43, 43));
        jTextArea5.setColumns(20);
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("Razão Social: Ulta Beauty Inc.\nTipo: Empresa de Capital Aberto\n\nUlta Beauty Inc. (anteriormente conhecida como Ulta Salon, Cosméticos e Fragrâncias Inc. até janeiro de 2017), é uma cadeia de lojas de beleza nos Estados Unidos, com sede em Bolingbrook, Illinois.Ulta Beauty carrega marcas de cosméticos e cuidados com a pele, fragrâncias masculinas e femininas e produtos capilares. Cada loja também é equipada com um salão de beleza.\nA Ulta Beauty oferece cosméticos, produtos para a pele e fragrâncias de alta qualidade e de farmácia, além de sua própria marca de maquiagem, produtos para banho e corpo, produtos para a pele, cabelos, esmaltes e fragrâncias.");
        jTextArea5.setWrapStyleWord(true);
        jScrollPane10.setViewportView(jTextArea5);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ulta-logo.png"))); // NOI18N

        jButton4.setText("Próximo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_BalancoUltaBeautyLayout = new javax.swing.GroupLayout(Panel_BalancoUltaBeauty);
        Panel_BalancoUltaBeauty.setLayout(Panel_BalancoUltaBeautyLayout);
        Panel_BalancoUltaBeautyLayout.setHorizontalGroup(
            Panel_BalancoUltaBeautyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BalancoUltaBeautyLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(Panel_BalancoUltaBeautyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_BalancoUltaBeautyLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane10))
                    .addGroup(Panel_BalancoUltaBeautyLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_BalancoUltaBeautyLayout.setVerticalGroup(
            Panel_BalancoUltaBeautyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BalancoUltaBeautyLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(Panel_BalancoUltaBeautyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(Panel_BalancoUltaBeautyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_BalancoUltaBeautyLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel24)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        Panel_Body.add(Panel_BalancoUltaBeauty, "card8");

        bg.add(Panel_Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1070, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Label_BalancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_BalancoMouseClicked
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card3");
    }//GEN-LAST:event_Label_BalancoMouseClicked

    private void Label_RelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_RelatorioMouseClicked
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card4");
    }//GEN-LAST:event_Label_RelatorioMouseClicked

    private void Label_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_HomeMouseClicked
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card2");
    }//GEN-LAST:event_Label_HomeMouseClicked

    private void Label_AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AboutMouseClicked
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card6");
    }//GEN-LAST:event_Label_AboutMouseClicked

    private void Label_AnalyticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AnalyticMouseClicked
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card5");
        
        CategoryDataset dataset = createDataset();
        JFreeChart chart = ChartFactory.createStackedAreaChart("", "", "", dataset);
        chart.setBackgroundPaint(new Color(43, 43, 43));
        chart.setBorderVisible(false);
        chart.setBorderPaint(new Color(54, 63, 73));
        chart.getCategoryPlot().setBackgroundPaint(new Color(43, 43, 43));
        chart.getCategoryPlot().setDomainGridlinePaint(new Color(54, 63, 73));
        chart.getCategoryPlot().setDomainGridlinesVisible(false);
        chart.getCategoryPlot().setOutlinePaint(new Color(54, 63, 73));

        ChartPanel cp = new ChartPanel(chart);
        cp.setBackground(new Color(43, 43, 43));

        panelChart.removeAll();
        panelChart.add(cp, BorderLayout.CENTER);
        panelChart.validate();
    }//GEN-LAST:event_Label_AnalyticMouseClicked

    private void Label_RelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_RelatorioMouseEntered
       Panel_Opcao3.setBackground(new java.awt.Color(51, 51, 51)); 
       Label_Relatorio.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N 
    }//GEN-LAST:event_Label_RelatorioMouseEntered

    private void Label_RelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_RelatorioMouseExited
       Panel_Opcao3.setBackground(new java.awt.Color(11, 12, 12));
       Label_Relatorio.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N 
    }//GEN-LAST:event_Label_RelatorioMouseExited

    private void Label_BalancoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_BalancoMouseEntered
        Panel_Opcao2.setBackground(new java.awt.Color(51, 51, 51));
        Label_Balanco.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N 
    }//GEN-LAST:event_Label_BalancoMouseEntered

    private void Label_BalancoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_BalancoMouseExited
        Panel_Opcao2.setBackground(new java.awt.Color(11, 12, 12));
        Label_Balanco.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
    }//GEN-LAST:event_Label_BalancoMouseExited

    private void Label_AnalyticMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AnalyticMouseEntered
       Panel_Opcao4.setBackground(new java.awt.Color(51, 51, 51)); 
       Label_Analytic.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N   
    }//GEN-LAST:event_Label_AnalyticMouseEntered

    private void Label_AnalyticMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AnalyticMouseExited
        Panel_Opcao4.setBackground(new java.awt.Color(11, 12, 12));
        Label_Analytic.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N 
    }//GEN-LAST:event_Label_AnalyticMouseExited

    private void Label_AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AboutMouseEntered
        Panel_Opcao5.setBackground(new java.awt.Color(51, 51, 51));
        Label_About.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N   
    }//GEN-LAST:event_Label_AboutMouseEntered

    private void Label_AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_AboutMouseExited
        Panel_Opcao5.setBackground(new java.awt.Color(11, 12, 12));
        Label_About.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N   
    }//GEN-LAST:event_Label_AboutMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card7");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card8");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout layout = (CardLayout)Panel_Body.getLayout();
        layout.show(Panel_Body,"card3");
    }//GEN-LAST:event_jButton4ActionPerformed
        
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                try{
          UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());}   
                catch (Exception e){
          e.printStackTrace();}
                new Principal().setVisible(true);
            }});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BP_Empresa1;
    private javax.swing.JTable BP_Empresa3;
    private javax.swing.JTable BP_Empresa4;
    private javax.swing.JLabel Icon_Bank;
    private javax.swing.JLabel Icon_Chart;
    private javax.swing.JLabel Icon_Chart1;
    private javax.swing.JLabel Icon_Chart2;
    private javax.swing.JLabel Icon_Home;
    private javax.swing.JLabel Icon_Money;
    private javax.swing.JLabel Label_About;
    private javax.swing.JLabel Label_Analytic;
    private javax.swing.JLabel Label_Analytics;
    private javax.swing.JLabel Label_Balanco;
    private javax.swing.JLabel Label_Heart;
    private javax.swing.JLabel Label_Home;
    private javax.swing.JLabel Label_Logo;
    private javax.swing.JLabel Label_Relatorio;
    private javax.swing.JLabel Label_We;
    private javax.swing.JPanel Panel_Analise;
    private javax.swing.JPanel Panel_BalancoAvon;
    private javax.swing.JPanel Panel_BalancoNatura;
    private javax.swing.JPanel Panel_BalancoUltaBeauty;
    private javax.swing.JPanel Panel_Body;
    private javax.swing.JPanel Panel_Opcao1;
    private javax.swing.JPanel Panel_Opcao2;
    private javax.swing.JPanel Panel_Opcao3;
    private javax.swing.JPanel Panel_Opcao4;
    private javax.swing.JPanel Panel_Opcao5;
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JPanel Panel_Relatorio;
    private javax.swing.JPanel Panel_Sobre;
    private javax.swing.JPanel SidePane;
    private javax.swing.JTable Tabela;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JPanel panelChart;
    // End of variables declaration//GEN-END:variables
}
